# Generated by Django 3.1.4 on 2020-12-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20201229_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
