# Generated by Django 3.1.4 on 2021-01-07 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20201231_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isVerified',
            new_name='isblocked',
        ),
        migrations.CreateModel(
            name='EmergencyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
