# Generated by Django 3.1.4 on 2021-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyotp',
            name='otp',
            field=models.CharField(max_length=255),
        ),
    ]
